### ISSUE TITLE
Potential Error With Users On < Typescript 3.7

### ISSUE THREAD

**Issue by srighankittu** [simonbengtsson/jsPDF-AutoTable#1008]
There is currently an issue when using 3.2.12 with a version less than typescript 3.7.
I am unable to upgrade to typescript 3.7 due to being stuck on Angular 8 for the time being.
The issue was builds failing due to the following error: 

ERROR in node_modules/jspdf-autotable/dist/index.d.ts:40:6 - error TS1086: An accessor cannot be declared in an ambient context

 get lineHeightFactor(): number;

When I remove the get from index.d.ts file, the code is working as expected without any issues.

**Comment by mmghv** [comment]
Although this could be a simple fix, it's not practical to stay compliant with all older versions of Typescript that users might be using.

You can simply set ` "skipLibCheck": true` in your [tsconfig.json](https://www.typescriptlang.org/tsconfig#skipLibCheck) to suppress the error if you can't upgrade.

```js
"compilerOptions": {
    "skipLibCheck": true
}
```

Let me know if this solves your problem.

**Comment by simonbengtsson** [comment]
I actually fixed a similar issue a while back by simply changing javascript getters to function getters. I don't remember what the issue was last time, but there was something related to that build configs became more complex as well. Submitted a potential fix now and released it in 3.7.1. Let me know if it works for you @srighankittu

**Comment by srighankittu** [comment]
@simonbengtsson Thanks for the quick update. Seems to be working fine now!!
