### ISSUE TITLE
Suggestion: Adding Title to Table to work with pageBreak.

### ISSUE THREAD

**Issue by Gustafssonz** [simonbengtsson/jsPDF-AutoTable#548]
SUGGESTION (forgot add label):
It would be nice to have a Title that will follow along with the table when breaking into a new page.

Today, if you want a nice title above your table you need to put text above your table. 
But the behavior of 'pageBreak' will not include Title, making it alone in the previous page. 

Add a way to add title with params for font-family, size, padding.

**Comment by Gustafssonz** [comment]
I have no idea what would be best since i'm a pleb developer. But I think it would be a smoother code and more logical to implement a simple 'tableHeader' attribute. 
Like:
tableHeader : {
    title: 'Tomten',
    font-family: 'Arial',
    color: 'white',
    font-size: 24
    padding-top: 8px
} 

Awesome Lib btw!

And then let it be attached

**Comment by simonbengtsson** [comment]
Thanks for the suggestion! Will consider it, but I would probably suggest we improve the didDrawCell instead for now. Mainly since table header might be confused with the table head. And also that it would drastically increase the API surface and library scope if we want to support full styling. It's better users learn `didDrawCell`, then they are free to draw any content with any style.

**Comment by simonbengtsson** [comment]
Seems that the `didDrawPage` hook are already only called if no content were added to the page because of `pageBreak: 'avoid'`. It would be nice to support titles of tables better, but for now I can't think of a good API for it so will close this ticket. Using didDrawPage should be fairly simple for most use cases.

**Comment by dimbslmh** [comment]
To check if a table was drawn on a new page you can do this:

```
didDrawPage: ({ cursor, doc, settings }) => {
  if (cursor.y < doc.lastAutoTable.finalY) {
    // do what you need here e.g. doc.text("Title", settings.margin.left, settings.margin.top)
  }
}
```
