### ISSUE TITLE
Text gets cut off if aligned to the right

### ISSUE THREAD

**Issue by Kritten** [simonbengtsson/jsPDF-AutoTable#620]
Hi, thanks for this great plugin!

If I set `halign: 'right'` to a cell/column, it cuts of the cellcontent, but only for some texts.

I prepared a fiddle which shows the issue for my very specific usecase:   
https://jsfiddle.net/nxd6q9zb/

"Anzahl der Wiederholungen (Verl. Opt.)" gets cut off. But if you change the content to something else it will most likely work properly.

Do you have any ideas how to solve this?

Oh and by the way, the README.md contains the typo `tabels` instead of `tables` in the API section. Should I create a pull request or are you going to fix this yourself? ;)

**Comment by mmghv** [comment]
It looks like a potential bug either with `AutoTable` or `jsPDF` itself, I also noticed it before with Arabic text.
Will investigate it after we finish working on an improvement regarding columns width calculations.

About the type, will fix it with next `README.md` changes, or you can send a PR if you want to :)

**Comment by mmghv** [comment]
It seems that the problem is with `jsPDF`, and it got nothing to do with `halign`, it also happens only with the latest version of `jsPDF` (which is not actually tagged as a release and not available via npm)

The problem specifically is with the function `getTextWidth()` from `jsPDF`, but with certain text only .. here's an example to reproduce it :

```js
  const doc = new jsPDF('p', 'mm');

  const text = 'Anzahl der Wiederholungen (Verl. Opt.)';
  const width = doc.getTextWidth(text);
  doc.text(text, 10, 15)

  doc.setDrawColor('red');
  doc.rect(10, 10, width+1, 7);
```

using the last tagged version `1.5.3` (https://unpkg.com/jspdf@1.5.3/dist/jspdf.debug.js) it gives this result :

![1](https://user-images.githubusercontent.com/5418859/78422559-6912d000-7660-11ea-9823-463b2b3cbd40.jpg)

but using the latest version from `master` (https://rawgit.com/MrRio/jsPDF/master/dist/jspdf.debug.js) it gives this result :

![2](https://user-images.githubusercontent.com/5418859/78422591-9f504f80-7660-11ea-91c5-b26cbcfce379.jpg)

So they seem to have some bugs in the latest version, also the releases are not getting tagged I don't know why, so just stick with the last tagged version `1.5.3` until they get back on track.
