### ISSUE TITLE
Issue with AutoTable and Large Amounts of Data

### ISSUE THREAD

**Issue by zaltanallc** [simonbengtsson/jsPDF-AutoTable#627]
### Description

I'm running into an issue creating PDFs from large amounts of data. This issue is that all browsers will display a "detected a long-running script" snackbar at the bottom with a request to disable the long-running script. Using Chrome Developer Tools, I've tracked it down to calling `jsPdf.autoTable()`, but that's as far as I've gotten.

### Environment

* jspdf 1.4.1
* jspdf-autotable 2.3.5

### Data Metrics

I don't know the exact minimum upper-bound of the issue, but I'm getting this issue for:

Initial data:
* ~26 MB data
* 12 columns
* 103,000 rows
* Conditional styles for each row/column

End report:
* 3,000 page PDF (eventually created if I wait long enough)
* End report size is 200MB

I'd also like to note that I would not like to run this in the browser, but my client is giving me no choice (yet).

Let me know if I can provide any more information about the problem

*edit*: Add versions

**Comment by mmghv** [comment]
What do you expect it to do?
it's processing and drawing this huge amount of data, it should take long time so calling it a "long-running script" is normal.

**Comment by zaltanad** [comment]
> What do you expect it to do?
> it's processing and drawing this huge amount of data, it should take long time so calling it a "long-running script" is normal.

Yep, you are totally right. However, I was wondering if we could implement the use of a [Continuation mechanism](https://en.wikipedia.org/wiki/Continuation) to release the browser thread to work on other processes. My browser loading animations aren't spinning because `.autotable()` is taking up all of the thread's attention

**Comment by mmghv** [comment]
> My browser loading animations aren't spinning

That's strange, it shouldn't be render-blocking.
Maybe trying to use web-workers would fix this problem and be more user-friendly.

Check out this [example ](https://github.com/jstarcher/webworker_jspdf_example) for using web-workers with `jspdf`.

**Comment by zaltanad** [comment]
> That's strange, it shouldn't be render-blocking.
> Maybe trying to use web-workers would fix this problem and be more user-friendly.
> 
> Check out this [example ](https://github.com/jstarcher/webworker_jspdf_example) for using web-workers with `jspdf`.

Thanks for the reference. Give me a few days and I'll try to implement it. If it works, I'll close this Issue

**Comment by zaltanallc** [comment]
So I can see that the vanilla `jsPDF` library will work inside of a Web Worker. However, because Web Workers cannot have access to the DOM, the Web Worker will not be able to access global variables like `document` and `window`. Does this mean that `jspdf` will be able to work in a Web Worker, but not `jspdf-autotable`?

I have a script which imports `jspdf.plugin.autotable.js` (version 2.3.5), but it's complaining with:
```
Uncaught ReferenceError: window is not defined
    at jspdf.plugin.autotable.js:19
```

**Comment by mmghv** [comment]
Autotable itself should work in the web worker (the latest version at least, I don't know about the old version you mentioned) , it doesn't need the DOM to work, you can create a table using data array, but jspdf is the one requires `window` to work, in the web worker example he seems to be using an old version (1.2), this old version may not work probably with autotable, so that's what you need to do some research on, how to make jspdf (1.5) work in web workers.

**Comment by zaltanallc** [comment]
Yeah, that's what I've been seeing. Thanks for the reference link and your insight. Hopefully this will help someone else.
