### ISSUE TITLE
PDF Creation Performance

### ISSUE THREAD

**Issue by zaltanallc** [simonbengtsson/jsPDF-AutoTable#636]
I was looking through the source code for the `autotable` function and the table data is arranged as an array of Objects (this is logical).

This array is treated as a queue in functional programming and goes from 0 to array.length - 1. However, in terms of memory allocation and garbage collection, the rows from [0, n] are still referenced in memory and are not eligible for garbage collection.

_Would it be possible to flip the internal workings so that the first row is stored last? The implementation can pop off each row from the stack and then deallocate the memory that it consumed._

Edit: The main thing I've noticed is that my table data consumes 40 MB of strings. Additionally, each PDF page that is created also holds memory as well. Once a PDF page is created and appended to the larger PDF object, is it possible to deallocate that as well? I realize that this runs in a loop and the previous stack memory allocations (pdf page) are eligible for garbage collection

**Comment by simonbengtsson** [comment]
Interesting! I assume you are running into issues regarding creation of huge tables with many rows? Or can you talk more about your use case and maybe provide an example?

I'm not sure simply garbage collecting one row at a time after it is drawn would help much to increase performance. The parsing and calculation stages of the plugin currently needs to have the entire table in memory anyway. The entire table is also semi expose to the user in the hooks data. It would certainly be interesting trying out ways to do parsing, calculations and drawing of one page at a time though to increase performance!

Also interesting regarding the 40mb of memory footprint. It would be interesting to know the difference in memory footprint between the internal representation of the table data and the raw input data. If there is a big difference between those there could be many low hanging performances fixes we could apply without having to restructure too much. 

I don't think anyone have made a thorough performance review of the plugin so any research or PRs related to this is very welcome. @mmghv made one great performance improvement not too long ago regarding rendering so he might have more info.

**Comment by mmghv** [comment]
There is certainly a big room for improvement in the plugin currently, regarding memory usage and probably a chance to chunk-printing the table .. but looking to how things are currently done in the plugin, automatic chunking could require some big changes in the code.

In my opinion the best available solution right now is to let the developer himself chunk the table manually, that can be done easily by splitting the table into chunks and drawing each chunk in a table and leaving no space between them, it will just result in repeating the header between chunks, but that's perfectly okay IMO.

Between each chunk the developer can await for some small delay to give the main thread control for a little bit allowing rendering of the page between chunks, also this will help greatly in memory usage, because each chunk will be eligible for garbage collection (I'm taking about the internal memory usage of the plugin, not the actual drawn pages).

Here's an example illustrating the solution, I'm able to draw a progress bar that get updated between chunks :
https://codepen.io/mmghv/pen/bGVpoxX?editors=1010

Here's the downloadable example file :
[chunks.zip](https://github.com/simonbengtsson/jsPDF-AutoTable/files/4490773/chunks.zip)

**Comment by mmghv** [comment]
Related to #627

**Comment by zaltanallc** [comment]
> Interesting! I assume you are running into issues regarding creation of huge tables with many rows?

Yep, this is the case. Normally I would suggest doing this on a server, but the client has pushed back many times and insisted that PDF creation happen in the browser. Basically we're creating financial reports with a lot of data, and almost each cell of data is unique.

> In my opinion the best available solution right now is to let the developer himself chunk the table manually, that can be done easily by splitting the table into chunks and drawing each chunk in a table and leaving no space between them, it will just result in repeating the header between chunks, but that's perfectly okay IMO.

The repeated header is actually a requirement, and another dev and I came across some difficulty with declaring repeated styles in order to get this done. Chunking the table page-by-page will actually reduce the amount of code that we write, so I think this is pretty much the best-case scenario

> I don't think anyone have made a thorough performance review of the plugin so any research or PRs related to this is very welcome. @mmghv made one great performance improvement not too long ago regarding rendering so he might have more info.

I'll see if I can provide any input on this because I ran some memory profiling (it took like 30 minutes for a 2 minute job because Chrome Dev Tools also took up resources), and for our largest reports, about 80% of our function runtime (which includes calculating subtotals, grand totals, conditional styling, etc), was in jsPDF-AutoTable creating each page.

Something I did notice was that for ~27 MB raw data, jsPDF-AutoTable was taking up to 1.5GB heap memory, which was pretty alarming. And this is on Chrome. I am betting that IE would crap out way earlier

**Comment by mmghv** [comment]
> Chunking the table page-by-page will actually reduce the amount of code that we write, so I think this is pretty much the best-case scenario.

Just keep in mind that we wait for a delay between each chunk, so chunking by **only** one page for large data will add a long delay for the whole script to finish, for example if the delay is 10ms (which I think is close to the minimum value for js timers) and you have 200mb pdf file of about 10,000 pages, you will add additional 100 seconds just for delays between pages.

So either use the biggest chunk that keeps the browser responsive (for example 15 pages), or consider using [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) instead of `setTimeOut` delays with a small chunk, which will result in a very tiny delay between chunks adding almost no additional time cost to the whole process, which honestly is the better method of doing this kind of things, I just took the easier approach with `setTimeOut` to illustrate the point.

**Comment by mmghv** [comment]
> I just took the easier approach with setTimeOut

I was actually stupid, it literally took no more than replacing `setTimeOut` with `requestAnimationFrame` and removing the delay arg, now you can specify the minimum reasonable chunk size (probably a page size) and it will add almost no additional time to the script, the idea is that it doesn't do any waiting or painting when the page doesn't need to, so the processing power can be utilized to its maximum allowing fast executing, almost identical to if you did no chunking.

[codepen ](https://codepen.io/mmghv/pen/bGVpoxX?editors=1010) is updated.

**Comment by zaltanallc** [comment]
> > I just took the easier approach with setTimeOut
> 
> I was actually stupid, it literally took no more than replacing `setTimeOut` with `requestAnimationFrame` and removing the delay arg, now you can specify the minimum reasonable chunk size (probably a page size) and it will add almost no additional time to the script, the idea is that it doesn't do any waiting or painting when the page doesn't need to, so the processing power can be utilized to its maximum allowing fast executing, almost identical to if you did no chunking, and this approach actually gives the maximum responsiveness to the page.
> 
> [codepen ](https://codepen.io/mmghv/pen/bGVpoxX?editors=1010) is updated.

Thank you for the reference. I have a working prototype for my client and it seems like it will fit our use-case. In terms of raw metrics, chunking the report takes slightly longer than if we were to do it all in one go, but at least we've reduced the chances of the client's browser crashing when trying to create reports in the browser.
