### ISSUE TITLE
text overlapping with autotable (Question)

### ISSUE THREAD

**Issue by a7son** [simonbengtsson/jsPDF-AutoTable#944]
I have this code

```javascript
function generate() {
        var doc = new jspdf.jsPDF()

        // Simple data example
        var head = [['ID', 'Country', 'Rank', 'Capital']]
        var body = [
          [1, 'Denmark', 7.526, 'Copenhagen'],
          [2, 'Switzerland', 7.509, 'Bern'],
          [3, 'Iceland', 7.501, 'Reykjavík'],
        ]
        doc.autoTable({ head: head, body: body })
        var finalY = doc.lastAutoTable.finalY || 10;
        doc.text('From javascript arrays', 14, finalY + 15);

        var head = [['ID', 'Country', 'Rank', 'Capital']]
        var body = [
          [1, 'Denmark', 7.526, 'Copenhagen'],
          [2, 'Switzerland', 7.509, 'Bern'],
          [3, 'Iceland', 7.501, 'Reykjavík'],
        ]
        doc.autoTable({ head: head, body: body })
        // Simple html example
        // doc.autoTable({ html: '#dataTable' })

        doc.save('table.pdf')
      }
```
i dont know why, the text from javascript array is always overlapping with 2nd table
did i do something wrong with code?
thanks before

the image is linke this[
[table-19.pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/10431186/table-19.pdf)
](url)

**Comment by mirajhad** [comment]
It looks like the issue is that you are creating the same table twice in a row, with the same head and body data. This will cause the second table to be placed directly on top of the first one, which will cause the text you added afterwards to overlap with the second table.

To fix this, you can either remove the second table creation, or change the data for the second table to be different from the first. If you want to create multiple tables, you can use different variables for each table's head and body data, so that they don't overlap each other.

Also, you can use the doc.addPage() before adding second table to avoid the overlapping.

**Comment by diego-rapoport** [comment]
What about using the html option with two different tables and different ids? In my case I have some dynamic data being rendered through angular, but only the second table added is being fulfilled.
